---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflare-public-ddns-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloudflare-public-ddns
  template:
    metadata:
      labels:
        app: cloudflare-public-ddns
    spec:
      containers:
        - name: cloudflare-public-ddns
          image: oznu/cloudflare-ddns
          env:
            - name: ZONE
              value: lazz.tech
            - name: SUBDOMAIN
              value: "*.public"
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: cloudflare
                  key: ddns-api-key
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
