---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: drone-runner-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drone-runner
  template:
    metadata:
      labels:
        app: drone-runner
    spec:
      containers:
        - name: drone-runner
          image: drone/drone-runner-docker:1
          env:
          - name: DRONE_GITEA_SERVER
            value: "https://git.internal.lazz.tech"
          - name: DRONE_RPC_HOST
            value: "drone.default.svc.cluster.local"
          - name: DRONE_RPC_SECRET
            valueFrom:
              secretKeyRef:
                name: drone
                key: drone-rpc-secret
          - name: DRONE_RUNNER_CAPACITY
            value: "2"
          - name: DRONE_RUNNER_NAME
            value: "Micro8 Container Runner"
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
          - containerPort: 3000
          volumeMounts:
          - mountPath: /data
            name: drone-data
          imagePullPolicy: IfNotPresent
      volumes:
        - name: drone-data
          hostPath:
            # directory location on host
            path: /opt/drone
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: drone-runner-service
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: tcp
  selector:
    app: drone-runner