---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homer
  template:
    metadata:
      labels:
        app: homer
    spec:
      containers:
        - name: homer
          image: b4bz/homer:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8080
          volumeMounts:
            - mountPath: www/assets/config.yml
              name: homer-config
              subPath: config.yml
            - mountPath: www/assets/icons
              name: homer-icons
          imagePullPolicy: IfNotPresent
      volumes:
        - name: homer-config
          configMap:
            name: homer-config
            items:
              - key: config.yml
                path: config.yml
        - name: homer-icons
          hostPath:
            # directory location on host
            path: /opt/homer/icons
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: homer-service
spec:
  ports:
  - port: 80
    targetPort: 8080
    name: tcp
  selector:
    app: homer
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: homer-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - 'internal.lazz.tech'
  rules:
  - host: internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: homer-service
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: homer-config
data:
  config.yml: |
    # See https://fontawesome.com/icons for icons options

    # Optional: Use external configuration file. 
    # Using this will ignore remaining config in this file
    # externalConfig: https://example.com/server-luci/config.yaml

    title: "App dashboard"
    subtitle: "Lazztech"
    # documentTitle: "Welcome" # Customize the browser tab text
    # logo: "assets/logo.png"
    # Alternatively a fa icon can be provided:
    icon: "fas fa-skull-crossbones"

    header: true # Set to false to hide the header
    footer: false # '<p>Created with <span class="has-text-danger">❤</span> with <a href="https://bulma.io/">bulma</a>, <a href="https://vuejs.org/">vuejs</a> & <a href="https://fontawesome.com/">font awesome</a> // Fork me on <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

    columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
    connectivityCheck: true # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example)

    # Optional theming
    theme: default # 'default' or one of the theme available in 'src/assets/themes'.

    # Optional custom stylesheet
    # Will load custom CSS files. Especially useful for custom icon sets.
    # stylesheet:
    #   - "assets/custom.css"

    # Here is the exaustive list of customization parameters
    # However all value are optional and will fallback to default if not set.
    # if you want to change only some of the colors, feel free to remove all unused key.
    colors:
      light:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#f5f5f5"
        card-background: "#ffffff"
        text: "#363636"
        text-header: "#424242"
        text-title: "#303030"
        text-subtitle: "#424242"
        card-shadow: rgba(0, 0, 0, 0.1)
        link-hover: "#363636"
        background-image: "assets/your/light/bg.png"
      dark:
        highlight-primary: "#3367d6"
        highlight-secondary: "#4285f4"
        highlight-hover: "#5a95f5"
        background: "#131313"
        card-background: "#2b2b2b"
        text: "#eaeaea"
        text-header: "#ffffff"
        text-title: "#fafafa"
        text-subtitle: "#f5f5f5"
        card-shadow: rgba(0, 0, 0, 0.4)
        link-hover: "#ffdd57"
        background-image: "assets/your/dark/bg.png"

    # Optional message
    message:
      # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
      style: "is-warning"
      title: "Work in Progress!"
      content: "Services may change and shouldn't be considered stable. Future announcements may be posted here."

    # Optional navbar
    # links: [] # Allows for navbar (dark mode, layout, and search) without any links
    links:
      - name: "Lazztech Status"
        icon: "fas fa-heartbeat"
        url: "https://status.internal.lazz.tech/"
        target: "_blank" # optional html tag target attribute
      - name: "Lazztech Blog"
        icon: "fas fa-blog"
        url: "https://lazz.tech/"
        target: "_blank" # optional html tag target attribute
      - name: "Infrastructure Repo"
        icon: "fab fa-github"
        url: "https://github.com/lazztech/Lazztech.Infrastructure"
        target: "_blank" # optional html tag target attribute
      - name: "Infrastructure Docs"
        icon: "fas fa-book-dead"
        url: "https://lazztech-infrastructure.netlify.app/"
        target: "_blank" # optional html tag target attribute

    # Services
    # First level array represent a group.
    # Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
    services:
      - name: "Community"
        icon: "fas fa-building"
        items:
          - name: "Nextcloud"
            logo: "assets/icons/nextcloud.png"
            subtitle: "Files, Chat, Productivity & Collaboration"
            tag: "community"
            url: "https://nextcloud.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Wiki"
            logo: "assets/icons/dokuwiki.svg"
            subtitle: "Community Wiki"
            tag: "community"
            url: "https://wiki.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "EBook Library"
            logo: "assets/icons/calibre.png"
            subtitle: "Community Ebook Libary & Reader"
            tag: "community"
            url: "https://read.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Snapdrop"
            logo: "assets/icons/snapdrop.png"
            subtitle: "The easiest way to transfer data across devices"
            tag: "community"
            url: "https://share.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Home Assistant"
            logo: "assets/icons/home-assistant.png"
            subtitle: "Home Automation"
            tag: "community"
            url: "https://home-assistant.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Jellyfin"
            logo: "assets/icons/jellyfin.png"
            subtitle: "Media server"
            tag: "community"
            url: "https://jellyfin.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet

      - name: "Lazztech Development"
        icon: "fas fa-code"
        items:
          - name: "dev-lazztechhub-service"
            icon: "fab fa-git-alt"
            subtitle: "Local development deployment"
            tag: "community"
            url: "https://dev-lazztechhub.internal.lazz.tech/graphql"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet

      - name: "Development Resources"
        icon: "fas fa-code"
        items:
          - name: "Adminer"
            logo: "assets/icons/adminer.png"
            subtitle: "Database Management"
            tag: "community"
            url: "https://adminer.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Gitea"
            logo: "assets/icons/gitea.png"
            subtitle: "Local Git mirror"
            tag: "community"
            url: "https://git.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Drone"
            logo: "assets/icons/drone.png"
            subtitle: "Container native Continous Integration /Continous Delivery"
            tag: "community"
            url: "https://cicd.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Docker Registry"
            logo: "assets/icons/docker.png"
            subtitle: "minimal registry:2 frontend"
            tag: "community"
            url: "https://docker.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Minio"
            logo: "assets/icons/minio.png"
            subtitle: "Object file storage"
            tag: "community"
            url: "https://objects.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet
          - name: "Code Server"
            logo: "assets/icons/code-server.png"
            subtitle: "VSCode web server"
            tag: "community"
            url: "https://code.internal.lazz.tech/"
            # class: "green" # optional custom CSS class for card, useful with custom stylesheet

      - name: "Monitoring"
        icon: "fas fa-heartbeat"
        items:
          - name: "Netdata"
            logo: "assets/icons/netdata.png"
            subtitle: "performance and health monitoring"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://192.168.1.11:19999/"
          - name: "Statping"
            logo: "assets/icons/statping.png"
            subtitle: "Uptime status and notifications"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://status.internal.lazz.tech/"
          - name: "Grafana"
            logo: "assets/icons/grafana.png"
            subtitle: "Monitoring & Visibility"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://grafana.internal.lazz.tech/"
          - name: "Prometheus"
            logo: "assets/icons/prometheus.png"
            subtitle: "Records real-time metrics"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://prometheus.internal.lazz.tech/"
          - name: "Scrutiny"
            logo: "assets/icons/scrutiny.svg"
            subtitle: "Hard Drive S.M.A.R.T Monitoring"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://scrutiny.internal.lazz.tech/"

      - name: "SysAdmin"
        icon: "fa fa-server"
        items:
          # - name: "Wireguard"
          #   logo: "assets/icons/wireguard.png"
          #   subtitle: "Wireguard VPN Management"
          #   tag: "sysadmin"
          #   # Optional tagstyle
          #   tagstyle: "is-success"
          #   url: "https://wireguard.internal.lazz.tech/"
          - name: "FreeIPA"
            logo: "assets/icons/freeipa.png"
            subtitle: "Identity Management"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://ipa.internal.lazz.tech/"
          - name: "Keycloak"
            logo: "assets/icons/keycloak.png"
            subtitle: "Identity Management"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://keycloak.internal.lazz.tech/"
          - name: "Unifi"
            logo: "assets/icons/unifi.jpg"
            subtitle: "Network Management"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://unifi/"
          - name: "Frigate"
            logo: "assets/icons/frigate.png"
            subtitle: "Security camera object detection"
            tag: "sysadmin"
            # Optional tagstyle
            tagstyle: "is-success"
            url: "https://frigate.internal.lazz.tech/"
          