---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextcloud-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nextcloud
  template:
    metadata:
      labels:
        app: nextcloud
    spec:
      containers:
        - name: nextcloud
          image: nextcloud:stable-apache
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/Los_Angeles
          volumeMounts:
            - mountPath: /var/www/html
              name: nextcloud-data
          imagePullPolicy: IfNotPresent
      volumes:
        - name: nextcloud-data
          hostPath:
            # directory location on host
            path: /opt/nextcloud/
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud-service
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  selector:
    app: nextcloud
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: nextcloud-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
  rules:
  - host: nextcloud.internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: nextcloud-service
          servicePort: 80