---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgweb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgweb
  template:
    metadata:
      labels:
        app: pgweb
    spec:
      containers:
        - name: pgweb
          image: sosedoff/pgweb
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
          - containerPort: 8081
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: pgweb-service
spec:
  ports:
  - port: 80
    targetPort: 8081
    name: tcp
  selector:
    app: pgweb
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pgweb-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
spec:
  tls:
    - secretName: internal-acme-crt-secret
      hosts:
        - '*.internal.lazz.tech'
  rules:
  - host: pgweb.internal.lazz.tech
    http:
      paths:
      - backend:
          serviceName: pgweb-service
          servicePort: 80