---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible
  template:
    metadata:
      labels:
        app: plausible
    spec:
      containers:
        - name: plausible
          image: plausible/analytics:latest
          env:
            - name: ADMIN_USER_EMAIL
              value: gianlazzarini@gmail.com
            - name: ADMIN_USER_NAME
              value: admin
            - name: ADMIN_USER_PWD
              valueFrom:
                secretKeyRef:
                  name: plausible
                  key: admin-password
            - name: BASE_URL
              value: plausible.lazz.tech
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: plausible
                  key: secret-key-base
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          imagePullPolicy: IfNotPresent
        - name: plausible-events-db
          image: yandex/clickhouse-server:21.3.2.5
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          volumeMounts:
          - mountPath: /var/lib/clickhouse
            name: plausible-data
          - mountPath: /etc/clickhouse-server/config.d/logging.xml
            name: plausible-clickhouse-config
            subPath: logging.xml
            readOnly: true
          - mountPath: /etc/clickhouse-server/users.d/logging.xml
            name: plausible-clickhouse-user-config
            subPath: logging.xml
            readOnly: true
          imagePullPolicy: IfNotPresent
      volumes:
      - name: plausible-data
        persistentVolumeClaim:
          claimName: plausible-pvc
      - name: plausible-clickhouse-config
        configMap:
          name: plausible-config
          items:
            - key: clickhouse-config.xml
              path: clickhouse-config.xml
      - name: plausible-clickhouse-user-config
        configMap:
          name: plausible-config
          items:
            - key: clickhouse-user-config.xml
              path: clickhouse-user-config.xml
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plausible-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: plausible-service
spec:
  ports:
  - port: 80
    targetPort: 3000
    name: tcp
  selector:
    app: plausible
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ackee-lazztech-ingress
  annotations:
    kubernetes.io/ingress.class: "traefik"
    traefik.ingress.kubernetes.io/redirect-entry-point: https
spec:
  tls:
    - secretName: lazztech-acme-crt-secret
      hosts:
        - 'lazz.tech'
  rules:
  - host: analytics.lazz.tech
    http:
      paths:
      - backend:
          serviceName: ackee-service
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plausible-config
data:
  clickhouse-config.xml: |
    <yandex>
        <logger>
            <level>warning</level>
            <console>true</console>
        </logger>

        <!-- Stop all the unnecessary logging -->
        <query_thread_log remove="remove"/>
        <query_log remove="remove"/>
        <text_log remove="remove"/>
        <trace_log remove="remove"/>
        <metric_log remove="remove"/>
        <asynchronous_metric_log remove="remove"/>
    </yandex>
  clickhouse-user-config.xml: |
    <yandex>
        <profiles>
            <default>
                <log_queries>0</log_queries>
                <log_query_threads>0</log_query_threads>
            </default>
        </profiles>
    </yandex>