- hosts: micro8
  tasks:
# deploy reverse proxy
  - name: Deploy Traefik
    block:
      - name: Copy Traefik Nomad Job
        copy:
          src: ../../jobs/traefik.nomad
          dest: /tmp/traefik.nomad
      - name: Run Traefik Nomad Job
        command: nomad job run /tmp/traefik.nomad

# deploy startpage
  - name: Deploy Homer
    block:
      - name: Copy Homer Nomad Job
        copy:
          src: ../../jobs/homer.nomad
          dest: /tmp/homer.nomad
      - name: Run Homer Nomad Job
        command: nomad job run /tmp/homer.nomad

# deploy community nomad job services
  - name: Deploy Nextcloud
    block:
      - name: Copy Nextcloud Nomad Job
        copy:
          src: ../../jobs/nextcloud.nomad
          dest: /tmp/nextcloud.nomad
      - name: Run Nextcloud Nomad Job
        command: nomad job run /tmp/nextcloud.nomad

  - name: Deploy Dokuwiki
    block:
      - name: Copy Dokuwiki Nomad Job
        copy:
          src: ../../jobs/dokuwiki.nomad
          dest: /tmp/dokuwiki.nomad
      - name: Run Dokuwiki Nomad Job
        command: nomad job run /tmp/dokuwiki.nomad

  - name: Deploy Calibre Web
    block:
      - name: Copy Calibre Web Nomad Job
        copy:
          src: ../../jobs/calibre-web.nomad
          dest: /tmp/calibre-web.nomad
      - name: Run Calibre Web Nomad Job
        command: nomad job run /tmp/calibre-web.nomad

  - name: Deploy Snapdrop
    block:
      - name: Copy Snapdrop Nomad Job
        copy:
          src: ../../jobs/snapdrop.nomad
          dest: /tmp/snapdrop.nomad
      - name: Run Snapdrop Nomad Job
        command: nomad job run /tmp/snapdrop.nomad

  - name: Deploy Home Assistant
    block:
      - name: Copy Home Assistant Nomad Job
        copy:
          src: ../../jobs/home-assistant.nomad
          dest: /tmp/home-assistant.nomad
      - name: Run Home Assistant Nomad Job
        command: nomad job run /tmp/home-assistant.nomad

  - name: Deploy Jellyfin
    block:
      - name: Copy Jellyfin Nomad Job
        copy:
          src: ../../jobs/jellyfin.nomad
          dest: /tmp/jellyfin.nomad
      - name: Run Jellyfin Nomad Job
        command: nomad job run /tmp/jellyfin.nomad

# deploy development nomad job resources

  - name: Deploy Gitea
    block:
      - name: Copy Gitea Nomad Job
        copy:
          src: ../../jobs/gitea.nomad
          dest: /tmp/gitea.nomad
      - name: Run Gitea Nomad Job
        command: nomad job run /tmp/gitea.nomad

  - name: Deploy Drone
    block:
      - name: Copy Drone Nomad Job
        copy:
          src: ../../jobs/drone.nomad
          dest: /tmp/drone.nomad
      - name: Run Drone Nomad Job
        command: nomad job run /tmp/drone.nomad

  - name: Deploy Docker Registry
    block:
      - name: Copy Docker Registry Nomad Job
        copy:
          src: ../../jobs/docker-registry.nomad
          dest: /tmp/docker-registry.nomad
      - name: Run Docker Registry Nomad Job
        command: nomad job run /tmp/docker-registry.nomad

# deploy monitoring nomad job services
  - name: Deploy Statping
    block:
      - name: Copy Statpin Nomad Job
        copy:
          src: ../../jobs/statping.nomad
          dest: /tmp/statping.nomad
      - name: Run Statping Nomad Job
        command: nomad job run /tmp/statping.nomad

  - name: Deploy Grafana
    block:
      - name: Copy Grafana Nomad Job
        copy:
          src: ../../jobs/grafana.nomad
          dest: /tmp/grafana.nomad
      - name: Run Grafana Nomad Job
        command: nomad job run /tmp/grafana.nomad

  - name: Deploy Prometheus
    block:
      - name: Copy Prometheus Nomad Job
        copy:
          src: ../../jobs/prometheus.nomad
          dest: /tmp/prometheus.nomad
      - name: Run Prometheus Nomad Job
        command: nomad job run /tmp/prometheus.nomad

  - name: Deploy Scrutiny
    block:
      - name: Copy Scrutiny Nomad Job
        copy:
          src: ../../jobs/scrutiny.nomad
          dest: /tmp/scrutiny.nomad
      - name: Run Scrutiny Nomad Job
        command: nomad job run /tmp/scrutiny.nomad

# deploy sysadmin nomad job services

  - name: Deploy Wireguard
    block:
      - name: Copy Wireguard Nomad Job
        copy:
          src: ../../jobs/wg-access-server.nomad
          dest: /tmp/wg-access-server.nomad
      - name: Run Wireguard Nomad Job
        command: nomad job run /tmp/wg-access-server.nomad

  - name: Deploy Keycloak
    block:
      - name: Copy Keycloak Nomad Job
        copy:
          src: ../../jobs/keycloak.nomad
          dest: /tmp/keycloak.nomad
      - name: Run Wireguard Nomad Job
        command: nomad job run /tmp/keycloak.nomad 