---
  - name: Configure Unifi UDM
    hosts: udm
    remote_user: root
    gather_facts: False
    tasks:
# append hosts to hosts file
      # host infrastructure services
      - name: nomad host entry
        raw: echo '192.168.1.11    nomad.lazz.tech' >> /etc/hosts
      - name: taefik host entry
        raw: echo '192.168.1.11    traefik.lazz.tech' >> /etc/hosts
      - name: consul host entry
        raw: echo '192.168.1.11    consul.lazz.tech' >> /etc/hosts
      - name: vault host entry
        raw: echo '192.168.1.11    vault-ui.lazz.tech' >> /etc/hosts
      # start page
      - name: homer host entry
        raw: echo '192.168.1.11    home' >> /etc/hosts
      # community services
      - name: nextcloud host entry
        raw: echo '192.168.1.11    nextcloud.lazz.tech' >> /etc/hosts
      - name: wiki host entry
        raw: echo '192.168.1.11    wiki.lazz.tech' >> /etc/hosts
      - name: read host entry
        raw: echo '192.168.1.11    read.lazz.tech' >> /etc/hosts
      - name: share host entry
        raw: echo '192.168.1.11    share.lazz.tech' >> /etc/hosts
      - name: home-assistant host entry
        raw: echo '192.168.1.11    home-assistant.lazz.tech' >> /etc/hosts
      - name: jellyfin host entry
        raw: echo '192.168.1.11    jellyfin.lazz.tech' >> /etc/hosts
      # development services
      - name: git host entry
        raw: echo '192.168.1.11    git.lazz.tech' >> /etc/hosts
      - name: cicd host entry
        raw: echo '192.168.1.11    cicd.lazz.tech' >> /etc/hosts
      - name: registry host entry
        raw: echo '192.168.1.11    registry.lazz.tech' >> /etc/hosts
      - name: docker host entry
        raw: echo '192.168.1.11    docker.lazz.tech' >> /etc/hosts
      - name: code host entry
        raw: echo '192.168.1.11    code.lazz.tech' >> /etc/hosts
      # monitoring services
      - name: status host entry
        raw: echo '192.168.1.11    status.lazz.tech' >> /etc/hosts
      - name: grafana host entry
        raw: echo '192.168.1.11    grafana.lazz.tech' >> /etc/hosts
      - name: prometheus host entry
        raw: echo '192.168.1.11    prometheus.lazz.tech' >> /etc/hosts
      - name: scrutiny host entry
        raw: echo '192.168.1.11    scrutiny.lazz.tech' >> /etc/hosts
      # sysadmin services
      - name: wireguard host entry
        raw: echo '192.168.1.11    wireguard.lazz.tech' >> /etc/hosts
      - name: keycloack host entry
        raw: echo '192.168.1.11    keycloak.lazz.tech' >> /etc/hosts

# restart dnsmasq so the hosts file changes take effect
      - name: Tell dnsmasq to reload hosts
        raw: "pkill -HUP dnsmasq"

    # - name: Add mappings to /etc/hosts
    #   blockinfile:
    #     path: /etc/hosts
    #     block: |
    #       {{ item.ip }} {{ item.name }}
    #     marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.name }}"
    #   loop:
    #     - { name: home, ip: 192.168.1.11 }
    #     - { name: nomad.lazz.tech, ip: 192.168.1.11 }
    #     - { name: traefik.lazz.tech, ip: 192.168.1.11 }
    #     - { name: consul.lazz.tech, ip: 192.168.1.11 }
    #     - { name: vault-ui.lazz.tech, ip: 192.168.1.11 }
    #     - { name: code.lazz.tech, ip: 192.168.1.11 }
    #     - { name: registry.lazz.tech, ip: 192.168.1.11 }
    #     - { name: registry-ui.lazz.tech, ip: 192.168.1.11 }
    #     - { name: home-assistant.lazz.tech, ip: 192.168.1.11 }
    #     - { name: heimdall.lazz.tech, ip: 192.168.1.11 }
    #     - { name: homebridge.lazz.tech, ip: 192.168.1.11 }
    #     - { name: wireguard.lazz.tech, ip: 192.168.1.11 }
    #     - { name: wiki.lazz.tech, ip: 192.168.1.11 }
    #     - { name: share.lazz.tech, ip: 192.168.1.11 }
    #     - { name: chat.lazz.tech, ip: 192.168.1.11 }
    #     - { name: irc.lazz.tech, ip: 192.168.1.11 }
    #     - { name: grafana.lazz.tech, ip: 192.168.1.11 }
    #     - { name: read.lazz.tech, ip: 192.168.1.11 }



